name: 'Build and Publish to NPM'

on: workflow_dispatch

# on:
#   release:
#     types: [published, created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: mbjr-in-webapp
          path: .
      - name: Use Node.js '16.x'
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build-prod:copy
      - run: ls src/build/bundles
  #     # Setup .npmrc file to publish to npm
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_NIK }}