name: 'Build and Publish to NPM'

on:
  release:
    types: [published, created]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, '16.x']

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run build-prod:copy

  publish:
    runs-on: ubuntu-latest
    steps:
      -run: ls src/build/bundles
  #     - uses: actions/checkout@v2
  #     # Setup .npmrc file to publish to npm
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16.x'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_NIK }}